set_property -dict { PACKAGE_PIN H16   IOSTANDARD LVCMOS33 } [get_ports clk]; #IO_L13P_T2_MRCC_35 Sch=sysclk
create_clock -add -name sys_clk_pin -period 8.00 -waveform {0 4} [get_ports clk];#set

set_property IOSTANDARD LVCMOS33 [get_ports {op[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[31]}]
#set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
#set_property CLOCK_DEDICATED_ROUTE FALSE[get_nets clk_IBUF]


